// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Unpro

#ifndef _UNPRO_UI_H
#define _UNPRO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * fading_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * blink_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_bg_png);   // assets/bg.png
LV_IMG_DECLARE( ui_img_warning_png);   // assets/warning.png
LV_IMG_DECLARE( ui_img_status_png);   // assets/status.png
LV_IMG_DECLARE( ui_img_power_png);   // assets/power.png
LV_IMG_DECLARE( ui_img_wifi_png);   // assets/wifi.png

// FONTS
LV_FONT_DECLARE( ui_font_Digit);
LV_FONT_DECLARE( ui_font_Digitmain);
LV_FONT_DECLARE( ui_font_digi_small);
LV_FONT_DECLARE( ui_font_digismall);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
