// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Unpro

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_background = NULL;lv_obj_t *ui_warning = NULL;lv_obj_t *ui_status = NULL;lv_obj_t *ui_power = NULL;lv_obj_t *ui_wifi = NULL;lv_obj_t *ui_temp = NULL;lv_obj_t *ui_target = NULL;lv_obj_t *ui_otemp = NULL;lv_obj_t *ui_owin = NULL;lv_obj_t *ui_owin1 = NULL;lv_obj_t *ui_cost = NULL;
// event funtions
void ui_event_Screen1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      blink_Animation(ui_status, 0);
      fading_Animation(ui_warning, 0);
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_background = lv_img_create(ui_Screen1);
lv_img_set_src(ui_background, &ui_img_bg_png);
lv_obj_set_width( ui_background, LV_SIZE_CONTENT);  /// 170
lv_obj_set_height( ui_background, LV_SIZE_CONTENT);   /// 321
lv_obj_set_align( ui_background, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_background, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_background, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_warning = lv_img_create(ui_Screen1);
lv_img_set_src(ui_warning, &ui_img_warning_png);
lv_obj_set_width( ui_warning, LV_SIZE_CONTENT);  /// 125
lv_obj_set_height( ui_warning, LV_SIZE_CONTENT);   /// 19
lv_obj_set_x( ui_warning, 9 );
lv_obj_set_y( ui_warning, 105 );
lv_obj_set_align( ui_warning, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_warning, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_warning, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_status = lv_img_create(ui_Screen1);
lv_img_set_src(ui_status, &ui_img_status_png);
lv_obj_set_width( ui_status, LV_SIZE_CONTENT);  /// 11
lv_obj_set_height( ui_status, LV_SIZE_CONTENT);   /// 2
lv_obj_set_x( ui_status, -55 );
lv_obj_set_y( ui_status, -91 );
lv_obj_set_align( ui_status, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_status, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_status, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_power = lv_img_create(ui_Screen1);
lv_img_set_src(ui_power, &ui_img_power_png);
lv_obj_set_width( ui_power, LV_SIZE_CONTENT);  /// 11
lv_obj_set_height( ui_power, LV_SIZE_CONTENT);   /// 10
lv_obj_set_x( ui_power, 38 );
lv_obj_set_y( ui_power, -120 );
lv_obj_set_align( ui_power, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_power, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_power, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wifi = lv_img_create(ui_Screen1);
lv_img_set_src(ui_wifi, &ui_img_wifi_png);
lv_obj_set_width( ui_wifi, LV_SIZE_CONTENT);  /// 10
lv_obj_set_height( ui_wifi, LV_SIZE_CONTENT);   /// 10
lv_obj_set_x( ui_wifi, 53 );
lv_obj_set_y( ui_wifi, -120 );
lv_obj_set_align( ui_wifi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_temp = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_temp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temp, -26 );
lv_obj_set_y( ui_temp, -115 );
lv_obj_set_align( ui_temp, LV_ALIGN_CENTER );
lv_label_set_text(ui_temp,"23.5");
lv_obj_set_style_text_color(ui_temp, lv_color_hex(0xED6306), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_temp, &ui_font_Digitmain, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_target = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_target, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_target, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_target, 43 );
lv_obj_set_y( ui_target, -102 );
lv_obj_set_align( ui_target, LV_ALIGN_CENTER );
lv_label_set_text(ui_target,"24.0");
lv_obj_set_style_text_color(ui_target, lv_color_hex(0xF1C1A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_target, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_target, &ui_font_Digit, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_otemp = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_otemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_otemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_otemp, -22 );
lv_obj_set_y( ui_otemp, -24 );
lv_obj_set_align( ui_otemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_otemp,"24.0");
lv_obj_set_style_text_color(ui_otemp, lv_color_hex(0xF1C1A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_otemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_otemp, &ui_font_Digit, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_owin = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_owin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_owin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_owin, -22 );
lv_obj_set_y( ui_owin, 6 );
lv_obj_set_align( ui_owin, LV_ALIGN_CENTER );
lv_label_set_text(ui_owin,"24.0");
lv_obj_set_style_text_color(ui_owin, lv_color_hex(0xF1C1A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_owin, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_owin, &ui_font_Digit, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_owin1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_owin1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_owin1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_owin1, -22 );
lv_obj_set_y( ui_owin1, 35 );
lv_obj_set_align( ui_owin1, LV_ALIGN_CENTER );
lv_label_set_text(ui_owin1,"24.0");
lv_obj_set_style_text_color(ui_owin1, lv_color_hex(0xF1C1A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_owin1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_owin1, &ui_font_Digit, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cost = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_cost, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_cost, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_cost, -32 );
lv_obj_set_y( ui_cost, -70 );
lv_obj_set_align( ui_cost, LV_ALIGN_CENTER );
lv_label_set_text(ui_cost,"24.0");
lv_obj_set_style_text_color(ui_cost, lv_color_hex(0xF1C1A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_cost, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_cost, &ui_font_digismall, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_background= NULL;
ui_warning= NULL;
ui_status= NULL;
ui_power= NULL;
ui_wifi= NULL;
ui_temp= NULL;
ui_target= NULL;
ui_otemp= NULL;
ui_owin= NULL;
ui_owin1= NULL;
ui_cost= NULL;

}
