// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Unpro

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_background;
extern lv_obj_t *ui_warning;
extern lv_obj_t *ui_status;
extern lv_obj_t *ui_power;
extern lv_obj_t *ui_wifi;
extern lv_obj_t *ui_temp;
extern lv_obj_t *ui_target;
extern lv_obj_t *ui_otemp;
extern lv_obj_t *ui_owin;
extern lv_obj_t *ui_owin1;
extern lv_obj_t *ui_cost;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

